affirmations = [
        "The possibilites are endless",
        "Today will be a good day",
        "You got this",
        "You'll figure it out",
        "You're a smart cookie",
        "I believe in you",
        "Mistakes don't make you less capable",
        "If everything was easy, you'd be bored",
        "I admire you for taking this on",
        "You'll find a way",
        "I know you'll sort it out",
        "It'll feel magical when it's working",
        "I'm rooting for you",
        "Your mind is full of brilliant ideas",
        "You make a difference in the world by simply existing",
        "You know more than you knew yesterday",
        "You can do it",
        "It's not a sprint, it's a marathon. One step at a time.",
        "Maybe if you knew enough about it, you wouldn't be afraid",
        "Small progress is still progress",
        "Don't worry about the past, you've evolved",
        "Starting is the most difficult step - but you can do it",
        "Don't forget to enjoy the journey",
        "A mistake is a learning opportunity",
        "You have the freedom to choose",
        "Relentless action turns thoughts into reality",
        "Don't be afraid to ask for help",
        "You're more helpful than you realize",
        "Everyone's always happy to have you around",
        "You can take it at your own pace",
        "Even the smallest act of kindness can bring someone immense joy, and you have the power to make that difference",
        "You are the master of your fate, you are the captain of your soul",
        "You can do it, I have no doubt",
        "Let your hopes shape your future",
        "I enjoy my own company",
        "It's your time to shine",
        "My best moments are yet to come, and I'll work for them",
        "I will do my best, and I will not regret it",
        "I will focus on the good, and embrace the bad",
        "Life loves me",
        "I now go beyond other people’s fears and limitations",
        "I do not have to prove myself to anyone",
        "I welcome new ideas",
        "I have the courage to live my dreams",
        "I am better than I was yesterday",
        "My self-worth doesn't depend on what others think of me",
        "And this, is to go even further beyond"
]